// One flat config for the whole workspace: the published library (ui/), the demo
// app, and storybook. Previously only apps/demo was linted, which left the 29
// components and the MCP server — the code that actually ships — unchecked.
// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  {
    ignores: [
      '**/dist/*',
      '**/.expo/*',
      // Throwaway .tsx fixtures generated by ui/mcp/check-examples.ts
      'ui/mcp/.examples-check/*',
      // Generated by sb-rn-get-stories
      'apps/storybook/.rnstorybook/storybook.requires.ts',
    ],
  },

  expoConfig,

  {
    rules: {
      // The barrels intentionally re-export the same binding from two places —
      // `theme/index.ts` re-exports BrandProvider/useBrandConfig from `../brand`,
      // `icons/index.ts` re-exports the icon types from `../brand/brand-types`,
      // `use-breakpoint.ts` re-exports `breakpoints`. ES modules only drop a
      // star-exported name when it resolves to *different* bindings, which these
      // do not (verified: tsc resolves every one of them through `ui/index.ts`).
      // The rule flags the name collision without checking the binding.
      'import/export': 'off',
    },
  },

  {
    // The MCP SDK ships subpath exports that eslint-plugin-import's resolver
    // does not read; tsc and the esbuild bundle both resolve them fine.
    files: ['ui/mcp/**/*.ts'],
    rules: {
      'import/no-unresolved': ['error', { ignore: ['^@modelcontextprotocol/sdk/'] }],
    },
  },

  {
    // `Icons[library]` is the whole point of renderIcon — the library is chosen
    // at runtime. The rule cannot validate a computed key; TypeScript can, and
    // does.
    files: ['ui/icons/icon-utils.tsx'],
    rules: {
      'import/namespace': 'off',
    },
  },

  {
    // Optional peer dependencies are loaded through a guarded `require()` on
    // purpose — @react-native-community/slider and expo-symbols are declared
    // optional in peerDependenciesMeta, so a static import would break any
    // consumer that skipped them. The storybook reanimated mock does the same
    // to stub the native module.
    files: [
      'ui/components/**/*.tsx',
      'apps/storybook/.storybook/mocks/**',
    ],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  {
    // Storybook CSF puts hooks inside `render:` functions. They are components,
    // but the rule only recognises PascalCase declarations, so every stateful
    // story trips it.
    files: ['**/*.stories.tsx', 'apps/storybook/.storybook/**'],
    rules: {
      'react-hooks/rules-of-hooks': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },

  {
    // `useRef(new Animated.Value(x)).current` is the documented React Native way
    // to hold a stable animated value, and the rule cannot tell it apart from a
    // real mid-render ref read — it accounts for every hit in
    // progress-indicator.tsx and it tracks the unwrapped alias too.
    //
    // TODO: sidebar.web.tsx, drawer.tsx and app-tabs.web.tsx trip these rules on
    // genuine mutable-ref reads and a set-state-in-effect, not on the Animated
    // idiom. Those three are real and worth revisiting — see the audit notes.
    files: ['ui/**/*.tsx'],
    rules: {
      'react-hooks/refs': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
]);
